uint32 frameIndex

float32[3] hips

float32[3] left_Shoulder
float32[3] leftArm
float32[3] leftForeArm

float32[3] right_Shoulder
float32[3] rightArm
float32[3] rightForeArm

float32 leftOmoplate
float32 leftShoulder
float32 leftRotate

# RightHand
float32 rightHand
float32 rightHandThumb 			# RightHandThumb{1,2,3}
float32 rightHandIndex 			# RightInHandIndex, RightHandIndex{1,2,3}
float32 rightHandMiddle 		# RightInHandMiddle, RightHandMiddle{1,2,3}
float32 rightHandRing 			# RightInHandRing, RightHandRing{1,2,3}
float32 rightHandPinky 			# RightInHandPinky, RightHandPinky{1,2,3}

# LeftHand
float32 leftHand 				# LeftHand
float32 leftHandThumb 			# LeftHandThumb{1,2,3}
float32 leftHandIndex 			# LeftInHandIndex, LeftHandIndex{1,2,3}
float32 leftHandMiddle 			# LeftInHandMiddle, LeftHandMiddle{1,2,3}
float32 leftHandRing 			# LeftInHandRing, LeftHandRing{1,2,3}
float32 leftHandPinky 			# LeftInHandPinky, LeftHandPinky{1,2,3}

